package wdsr.exercise5;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class CreateDatabase {
	Connect conn = new Connect();
	Connection con = conn.getConnection();
	
	public void createTables(){
		try {
			Statement st = con.createStatement();
			st.executeUpdate("create table Student("
			+ "pkey INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,"
			+ " name VARCHAR(30),"
			+ " sex VARCHAR(6),"
			+ " age INTEGER,"
			+ " level INTEGER);");
			st.executeUpdate("create table Faculty("
					+ "pkey INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,"
					+ " name VARCHAR(30));");
			st.executeUpdate("create table Class("
					+ "pkey INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1000, INCREMENT BY 1) PRIMARY KEY,"
					+ " name VARCHAR(30),"
					+ " fkey_faculty INTEGER,"
					+ " FOREIGN KEY(fkey_faculty) REFERENCES Faculty(pkey));");
			st.executeUpdate("create table Enrollment("
					+ " fkey_student INTEGER,"
					+ " fkey_class INTEGER,"
					+ " FOREIGN KEY(fkey_student) REFERENCES Student(pkey),"
					+ " FOREIGN KEY(fkey_class) REFERENCES Class(pkey));");
			System.out.print("Database created \n");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	public void dropTables(){
		Statement st;
		try {
			st = con.createStatement();
			st.executeUpdate("DROP TABLE Enrollment");
			st.executeUpdate("DROP TABLE Class");
			st.executeUpdate("DROP TABLE Faculty");
			st.executeUpdate("DROP TABLE Student");
			System.out.print("Database droped \n");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}
	
	

}
